version = 1

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "project"

[analyzers.config]
cyclomatic_complexity_threshold = 31
exclude_patterns = [
  "GO-S1023"  # MD5 密码算法警告
]